import { expect, test } from '@playwright/test';

test('desktop editor primary workflow and publish viewer', async ({ page, context }, testInfo) => {
 test.skip(testInfo.project.name === 'mobile', 'Desktop editor is intentionally disabled on small screens');
 const logs:string[]=[]; const requests:string[]=[]; page.on('console',m=>{ if(['error','warning'].includes(m.type())) logs.push(`${m.type()}: ${m.text()}`); }); page.on('requestfailed',r=>requests.push(`${r.url()} ${r.failure()?.errorText}`));
 await page.goto('/'); await expect(page.locator('.brand')).toHaveText('SceneForge'); await expect(page.getByText('Hero Cube')).toBeVisible();
 await page.getByText('Hero Cube').click(); await page.getByLabel('Position x').fill('1.25'); await page.getByLabel('Position y').fill('1.5'); await page.getByLabel('Rotation y').fill('0.7'); await page.getByLabel('Scale x').fill('1.4'); await page.getByRole('button',{name:'Assets'}).click(); await page.getByRole('button',{name:'crystal-orb'}).click(); await page.getByLabel('Material preset').selectOption('glow'); await page.getByLabel('Base color').fill('#ffcc55'); await page.getByRole('button',{name:'Hover State'}).click(); await page.getByRole('button',{name:'Add keyframed spin'}).click(); await expect(page.getByLabel('Timeline track')).toBeVisible();
 await page.getByRole('button',{name:'Play'}).click(); await page.mouse.move(650,420); await page.mouse.click(650,420); await page.screenshot({path:`test-results/editor-play-${testInfo.project.name}.png`, fullPage:true}); await page.getByRole('button',{name:'Exit Play'}).click(); await page.waitForTimeout(800); await page.reload(); await expect(page.getByText('Hero Cube')).toBeVisible(); await expect(page.getByText('CC0 cc0-crystal-orb')).toBeVisible(); await page.screenshot({path:`test-results/editor-restored-${testInfo.project.name}.png`, fullPage:true});
 const [viewer] = await Promise.all([context.waitForEvent('page'), page.getByRole('button',{name:'Publish'}).click()]); await expect(page.getByTestId('publish-url')).toContainText('/viewer#'); await viewer.waitForLoadState('networkidle'); await expect(viewer.getByText('Public hash snapshot loaded')).toBeVisible(); await viewer.mouse.move(450,400); await viewer.mouse.click(450,400); await viewer.screenshot({path:`test-results/viewer-desktop-${testInfo.project.name}.png`, fullPage:true});
 expect(logs.filter(l=>!/THREE.WebGLRenderer|GL Driver Message|GPU stall due to ReadPixels/.test(l))).toEqual([]); expect(requests).toEqual([]);
});

test('mobile public viewer opens a real 3D scene', async ({ page }, testInfo) => { const requests:string[]=[]; page.on('requestfailed',r=>requests.push(r.url())); await page.goto('/viewer'); await expect(page.getByText('Public hash snapshot loaded')).toBeVisible(); await page.screenshot({path:`test-results/viewer-mobile-${testInfo.project.name}.png`, fullPage:true}); expect(requests).toEqual([]); });
