"use client";
import { Canvas, useFrame } from '@react-three/fiber';
import { Grid, OrbitControls, TransformControls, Bounds, Html, Line } from '@react-three/drei';
import { useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import type { SceneDocument, SceneNode } from '@/types';
import { applyAnimationSample, applyState } from '@/engine';

type Props={document:SceneDocument; selectedId?:string|null; hoveredId?:string|null; tool?:'translate'|'rotate'|'scale'; playMode?:boolean; onSelect?:(id:string|null)=>void; onHover?:(id:string|null)=>void; onTransform?:(id:string, patch:{position?:{x:number;y:number;z:number};rotation?:{x:number;y:number;z:number};scale?:{x:number;y:number;z:number}})=>void;};
function mat(doc:SceneDocument,node:SceneNode){ const m=node.materialId?doc.materials[node.materialId]:undefined; const color=m?.baseColor??'#8bb6ff'; const opacity=m?.opacity??1; const common={color,transparent:opacity<1,opacity,metalness:m?.metalness??0,roughness:m?.roughness??.55,emissive:m?.emissive??'#000'}; return common; }
function Geometry({node}:{node:SceneNode}){ const p=node.primitive; if(node.kind==='model'){ if(node.assetId?.includes('torus')) return <torusGeometry args={[.55,.16,16,48]}/>; if(node.assetId?.includes('diamond')) return <octahedronGeometry args={[.7]}/>; if(node.assetId?.includes('rocket')||node.assetId?.includes('tree')) return <coneGeometry args={[.55,1.2,24]}/>; if(node.assetId?.includes('column')) return <cylinderGeometry args={[.35,.35,1.4,32]}/>; return <sphereGeometry args={[.55,32,32]}/>; }
 if(p==='sphere') return <sphereGeometry args={[node.geometry.radius??.55,32,32]}/>; if(p==='cylinder') return <cylinderGeometry args={[.45,.45,1,32]}/>; if(p==='plane') return <planeGeometry args={[1,1]}/>; if(p==='text') return <boxGeometry args={[1.2,.18,.05]}/>; return <boxGeometry args={[node.geometry.width??1,node.geometry.height??1,node.geometry.depth??1]}/>; }
function Obj({doc,node,selected,hovered,play,onSelect,onHover}:{doc:SceneDocument;node:SceneNode;selected:boolean;hovered:boolean;play:boolean;onSelect?:(id:string)=>void;onHover?:(id:string|null)=>void}){ if(!node.visible) return null; if(node.kind==='light'){ return node.light?.type==='directional'?<directionalLight position={[node.position.x,node.position.y,node.position.z]} color={node.light.color} intensity={node.light.intensity}/>:<pointLight position={[node.position.x,node.position.y,node.position.z]} color={node.light?.color??'#fff'} intensity={node.light?.intensity??1}/>; } if(node.kind==='camera'||node.kind==='group') return null; const material=mat(doc,node); return <group position={[node.position.x,node.position.y,node.position.z]} rotation={[node.rotation.x,node.rotation.y,node.rotation.z]} scale={[node.scale.x,node.scale.y,node.scale.z]} onPointerOver={(e)=>{e.stopPropagation(); onHover?.(node.id)}} onPointerOut={(e)=>{e.stopPropagation(); onHover?.(null)}} onClick={(e)=>{e.stopPropagation(); onSelect?.(node.id)}} data-name={node.name}><mesh castShadow={node.castShadow} receiveShadow={node.receiveShadow}><Geometry node={node}/><meshStandardMaterial {...material}/></mesh>{(selected||hovered)&&<lineSegments><edgesGeometry args={[new THREE.BoxGeometry(1.12,1.12,1.12)]}/><lineBasicMaterial color={selected?'#76e4ff':'#ffcf5a'} /></lineSegments>}{play&&hovered&&<Html center><div style={{background:'#111827',border:'1px solid #ffcf5a',padding:4,borderRadius:6,fontSize:10}}>Hover state</div></Html>}</group> }
function RuntimeScene({baseDoc,...props}:Props&{baseDoc:SceneDocument}){ const [runtime,setRuntime]=useState(baseDoc); const [running,setRunning]=useState<{animId:string;start:number}|null>(null); useEffect(()=>setRuntime(baseDoc),[baseDoc]); useFrame(()=>{ if(running){ const anim=runtime.animations[running.animId]??baseDoc.animations[running.animId]; if(anim){ const elapsed=performance.now()-running.start; setRuntime(applyAnimationSample(baseDoc,anim,elapsed)); if(elapsed>anim.duration+anim.delay && !anim.loop) setRunning(null); } }}); const selected=props.selectedId; const nodes=Object.values(runtime.nodes); const handleEvent=(nodeId:string,event:'Hover'|'Mouse Leave'|'Click')=>{ if(!props.playMode){ if(event==='Click') props.onSelect?.(nodeId); return; } for(const inter of Object.values(baseDoc.interactions).filter(i=>i.nodeId===nodeId&&i.event===event)){ for(const a of inter.actions){ if(a.type==='Change State'){ const target=a.targetId; if(target) setRuntime(d=>applyState(d,target,a.stateId)); } if(a.type==='Play Animation' && a.animationId) setRunning({animId:a.animationId,start:performance.now()}); if(a.type==='Open Link' && a.url && /^https?:\/\//.test(a.url)) window.open(a.url,'_blank','noopener'); } } };
 return <><ambientLight intensity={.45}/>{nodes.map(n=><Obj key={n.id} doc={runtime} node={n} selected={n.id===selected} hovered={n.id===props.hoveredId} play={!!props.playMode} onSelect={(id)=>handleEvent(id,'Click')} onHover={(id)=>{props.onHover?.(id); if(id) handleEvent(id,'Hover'); else { const hid=props.hoveredId; if(hid) handleEvent(hid,'Mouse Leave'); }}}/>)}<Grid args={[20,20]} cellColor="#273246" sectionColor="#4b668f" fadeDistance={25}/><axesHelper args={[2]}/></> }
function TransformProxy({doc,selectedId,tool,onTransform}:{doc:SceneDocument;selectedId?:string|null;tool?:'translate'|'rotate'|'scale';onTransform?:Props['onTransform']}){ const ref=useRef<THREE.Mesh>(null); const node=selectedId?doc.nodes[selectedId]:undefined; useEffect(()=>{ if(ref.current&&node){ ref.current.position.set(node.position.x,node.position.y,node.position.z); ref.current.rotation.set(node.rotation.x,node.rotation.y,node.rotation.z); ref.current.scale.set(node.scale.x,node.scale.y,node.scale.z); }},[node]); if(!node||node.kind==='light'||node.kind==='camera'||node.locked) return null; return <TransformControls object={(ref.current??undefined) as any} mode={tool} onMouseUp={()=>{const o=ref.current; if(o) onTransform?.(node.id,{position:{x:o.position.x,y:o.position.y,z:o.position.z},rotation:{x:o.rotation.x,y:o.rotation.y,z:o.rotation.z},scale:{x:o.scale.x,y:o.scale.y,z:o.scale.z}})}}><mesh ref={ref} visible={false}><boxGeometry/><meshBasicMaterial/></mesh></TransformControls> }
export function SceneViewport(props:Props){ return <Canvas shadows camera={{position:[5,3.2,6],fov:48}} onPointerMissed={()=>props.onSelect?.(null)} gl={{antialias:true}} fallback={<div role="alert">WebGL is unavailable. SceneForge Viewer fallback: open on a WebGL capable browser.</div>}><color attach="background" args={[props.document.settings.background]}/><Bounds fit clip observe margin={1.2}><RuntimeScene baseDoc={props.document} {...props}/></Bounds>{!props.playMode&&<TransformProxy doc={props.document} selectedId={props.selectedId} tool={props.tool} onTransform={props.onTransform}/>}<OrbitControls makeDefault enabled={!props.playMode}/></Canvas> }
