import type { Animation, Easing, SceneDocument, SceneNode, Vec3 } from './types';
export const cloneDoc = (doc:SceneDocument): SceneDocument => structuredClone(doc);
export function clampFinite(n:number, fallback=0){ return Number.isFinite(n) ? n : fallback; }
export function safeScale(n:number){ const v=clampFinite(n,1); return Math.abs(v)<0.001 ? 0.001 : v; }
export function ease(t:number,e:Easing){ const x=Math.min(1,Math.max(0,t)); if(e==='linear')return x; if(e==='easeIn')return x*x; if(e==='easeOut')return 1-(1-x)*(1-x); return x<.5?2*x*x:1-Math.pow(-2*x+2,2)/2; }
const isVec=(v:unknown):v is Vec3=>!!v&&typeof v==='object'&&'x'in v&&'y'in v&&'z'in v;
export function lerpValue(a:unknown,b:unknown,t:number): unknown { if(typeof a==='number'&&typeof b==='number') return a+(b-a)*t; if(typeof a==='string'&&typeof b==='string') return t<.5?a:b; if(isVec(a)&&isVec(b)) return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t}; return t<.5?a:b; }
export function sampleAnimation(anim:Animation, elapsedMs:number){ const local = anim.loop ? ((elapsedMs-anim.delay)%anim.duration+anim.duration)%anim.duration : Math.min(anim.duration, Math.max(0, elapsedMs-anim.delay)); const out:Record<string,unknown>={}; for(const tr of anim.tracks){ const keys=[...tr.keyframes].sort((a,b)=>a.time-b.time); if(keys.length===0) continue; let a=keys[0], b=keys[keys.length-1]; for(let i=0;i<keys.length-1;i++){ if(local>=keys[i].time && local<=keys[i+1].time){ a=keys[i]; b=keys[i+1]; break; } } const span=Math.max(1,b.time-a.time); out[`${tr.nodeId}:${tr.property}`]=lerpValue(a.value,b.value,ease((local-a.time)/span,anim.easing)); } return out; }
export function applyState(doc:SceneDocument,nodeId:string,stateId?:string): SceneDocument { const next=cloneDoc(doc); const base=doc.nodes[nodeId]; if(!base) return next; const node=next.nodes[nodeId]; if(!stateId){ Object.assign(node, base); return next; } const st=doc.states[stateId]; if(!st) return next; if(st.transform?.position) node.position=st.transform.position; if(st.transform?.rotation) node.rotation=st.transform.rotation; if(st.transform?.scale) node.scale=st.transform.scale; if(typeof st.visibility==='boolean') node.visible=st.visibility; if(st.materialColor && node.materialId) next.materials[node.materialId].baseColor=st.materialColor; if(typeof st.opacity==='number' && node.materialId) next.materials[node.materialId].opacity=st.opacity; return next; }
export function applyAnimationSample(doc:SceneDocument, anim:Animation, elapsed:number): SceneDocument { const next=cloneDoc(doc); const sample=sampleAnimation(anim, elapsed); for(const [k,val] of Object.entries(sample)){ const [nodeId,prop]=k.split(':') as [string, string]; const node=next.nodes[nodeId]; if(node && (prop==='position'||prop==='rotation'||prop==='scale') && isVec(val)) (node[prop] as Vec3)=val; if(node && prop==='color' && typeof val==='string' && node.materialId) next.materials[node.materialId].baseColor=val; if(node && prop==='opacity' && typeof val==='number' && node.materialId) next.materials[node.materialId].opacity=val; } return next; }
export function validateOpenLink(url:string){ try{ const u=new URL(url); return u.protocol==='http:'||u.protocol==='https:'; }catch{return false;} }
